services:
  oracledb:
    build:
      dockerfile: oracle/Dockerfile
      context: .
    ports:
      - "1521:1521"
    volumes:
      - ./.data:/opt/oracle/oradata
  php:
    build:
      dockerfile: php/Dockerfile
      context: .
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
